// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwg0xHRXZ6ScbuSXVZ-n1HCd-nAnrrA8g',
    appId: '1:885804434260:web:7246cb17c1b196b5947ec1',
    messagingSenderId: '885804434260',
    projectId: 'plantlogin-a68ee',
    authDomain: 'plantlogin-a68ee.firebaseapp.com',
    storageBucket: 'plantlogin-a68ee.appspot.com',
    measurementId: 'G-C0SVE7LN93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MM2fx8lc2LQwkQkBLKKTOpyYx8Q687s',
    appId: '1:885804434260:android:87107aad0053eeba947ec1',
    messagingSenderId: '885804434260',
    projectId: 'plantlogin-a68ee',
    storageBucket: 'plantlogin-a68ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFG3EE6uE5cBhEF7H5lLs-GjTqWgU9aw',
    appId: '1:885804434260:ios:5d9e3713fe669d7e947ec1',
    messagingSenderId: '885804434260',
    projectId: 'plantlogin-a68ee',
    storageBucket: 'plantlogin-a68ee.appspot.com',
    iosBundleId: 'com.example.plantguardLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFG3EE6uE5cBhEF7H5lLs-GjTqWgU9aw',
    appId: '1:885804434260:ios:30fc9bdf617be60d947ec1',
    messagingSenderId: '885804434260',
    projectId: 'plantlogin-a68ee',
    storageBucket: 'plantlogin-a68ee.appspot.com',
    iosBundleId: 'com.example.plantguardLogin.RunnerTests',
  );
}
